# Generated by Django 4.2.2 on 2023-06-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0002_project_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='internships/'),
        ),
    ]
