# Generated by Django 4.2.2 on 2023-09-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPortfolio', '0003_alter_internships_image1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='achievement',
            options={'ordering': ['-year']},
        ),
        migrations.AlterModelOptions(
            name='internships',
            options={'ordering': ['-start_date']},
        ),
        migrations.AddField(
            model_name='internships',
            name='links',
            field=models.ManyToManyField(related_name='internships', to='MyPortfolio.link'),
        ),
        migrations.AddField(
            model_name='project',
            name='links',
            field=models.ManyToManyField(related_name='projects', to='MyPortfolio.link'),
        ),
    ]
